# Generated by Django 4.2.7 on 2025-06-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(blank=True, help_text='Código hexadecimal del color (ej. #FF5733)', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código único de la prenda', max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Precio de costo en ARS', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta en ARS', max_digits=10)),
                ('genero', models.CharField(choices=[('N', 'Neutro'), ('M', 'Masculino'), ('F', 'Femenino')], default='N', max_length=1)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='prendas/')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la prenda está disponible para la venta')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='prendas.categoria')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='prendas/')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='prendas.prenda')),
            ],
            options={
                'verbose_name': 'Imagen de Prenda',
                'verbose_name_plural': 'Imágenes de Prendas',
                'ordering': ['prenda', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='VariantePrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='variantes/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prendas.color')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='prendas.prenda')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prendas.talla')),
            ],
            options={
                'verbose_name': 'Variante de Prenda',
                'verbose_name_plural': 'Variantes de Prendas',
                'ordering': ['prenda', 'talla', 'color'],
                'unique_together': {('prenda', 'talla', 'color')},
            },
        ),
    ]
